# Generated by Django 6.0.7 on 2026-08-16 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payee_address_alter_payee_user_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='payer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='payer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='payer',
            name='user_name',
        ),
        migrations.AddField(
            model_name='payee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
