# Generated by Django 6.0.7 on 2026-08-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payee_first_name_remove_payee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payer'),
        ),
    ]
